# Sets the logging level, default is info.
org.slf4j.simpleLogger.defaultLogLevel=debug

# Sets the log output. "file/path" for file logging, or "System.out" and
# "System.err" for their respective console streams. System.err is default.
org.slf4j.simpleLogger.logFile=logs/log.log